<a href="https://colab.research.google.com/github/YaokunLin/KaggleCodes/blob/main/An_Intro_to_Vectorization_and%C2%A0TF_IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [ ]:
corpus = [
    'It is Monday today.',
    'It was Sunday yesterday.',
    'It will be Tuesday tomorrow.',
    'Which day of the week will it be on the day after tomorrow?',
]

X = vectorizer.fit_transform(corpus)
X_array=X.toarray()

In [ ]:
X

<4x18 sparse matrix of type '<class 'numpy.int64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [ ]:
X_array

array([[0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 1, 2, 0, 1, 0, 1, 1, 0, 2, 0, 1, 0, 0, 1, 1, 1, 0]])

In [ ]:
vectorizer.get_feature_names()

['after',
 'be',
 'day',
 'is',
 'it',
 'monday',
 'of',
 'on',
 'sunday',
 'the',
 'today',
 'tomorrow',
 'tuesday',
 'was',
 'week',
 'which',
 'will',
 'yesterday']

In [ ]:
vectorizer.vocabulary_.get('day')
#The converse mapping from feature name to column index is stored in the vocabulary_ attribute of the vectorizer

2

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer()

In [ ]:
count_matrix = [[3, 0, 1],
          [2, 0, 0],
          [3, 0, 0],
          [4, 0, 0],
          [3, 2, 0],
          [3, 0, 2]]

In [ ]:
tfidf = transformer.fit_transform(count_matrix)
tfidf.toarray()

array([[0.85151335, 0.        , 0.52433293],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.55422893, 0.83236428, 0.        ],
       [0.63035731, 0.        , 0.77630514]])

In [ ]:
transformer.idf_

array([1.        , 2.25276297, 1.84729786])